# Generated by Django 4.2.9 on 2024-01-05 12:28

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ingredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        error_messages={
                            "max_length": "Значение более 200 символов",
                            "unique": "Значение не уникально",
                        },
                        help_text="Укажите наименование",
                        max_length=200,
                        unique=True,
                        verbose_name="Наименование",
                    ),
                ),
                (
                    "measurement_unit",
                    models.CharField(
                        error_messages={"max_length": "Значение более 200 символов"},
                        help_text="Укажите единицу измерения",
                        max_length=200,
                        verbose_name="Единица измерения",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ингридиент",
                "verbose_name_plural": "Ингридиенты",
                "ordering": ("name",),
            },
        ),
    ]
