# Generated by Django 3.2.16 on 2024-01-04 08:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ingredients", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredient",
            name="measurement_unit",
            field=models.CharField(
                error_messages={"max_length": "Значение более 200 символов"},
                help_text="Укажите единицу измерения",
                max_length=200,
                verbose_name="Единица измерения",
            ),
        ),
        migrations.AlterField(
            model_name="ingredient",
            name="name",
            field=models.CharField(
                error_messages={
                    "max_length": "Значение более 200 символов",
                    "unique": "Значение не уникально",
                },
                help_text="Укажите наименование",
                max_length=200,
                unique=True,
                verbose_name="Наименование",
            ),
        ),
    ]
