# Generated by Django 3.2.16 on 2024-01-04 08:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tags", "0002_alter_tag_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(
                error_messages={"max_length": "Значение более 200 символов"},
                help_text="Укажите наименование",
                max_length=200,
                verbose_name="Наименование",
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="slug",
            field=models.SlugField(
                error_messages={
                    "max_length": "Значение более 200 символов",
                    "unique": "Значение не уникально",
                },
                help_text="Укажите слаг, поле должно быть уникальным",
                max_length=200,
                unique=True,
                verbose_name="Слаг",
            ),
        ),
    ]
