# Generated by Django 4.2.9 on 2024-01-07 08:16

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("ingredients", "0001_initial"),
        ("tags", "0003_auto_20240104_1102"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="Добавьте фотографию",
                        upload_to="recipe/images/",
                        verbose_name="Фотография",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        error_messages={"max_length": "Значение более 200 символов"},
                        help_text="Укажите наименование",
                        max_length=200,
                        verbose_name="Наименование",
                    ),
                ),
                (
                    "text",
                    models.CharField(
                        help_text="Добавьте описание",
                        max_length=1000,
                        verbose_name="Описание",
                    ),
                ),
                (
                    "cooking_time",
                    models.IntegerField(
                        help_text="Укажите время приготовления",
                        validators=[
                            django.core.validators.MinValueValidator(
                                1,
                                message="Время приготовления не может быть менее 1 минуты",
                            )
                        ],
                        verbose_name="Время приготовления",
                    ),
                ),
                (
                    "pub_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата публикации"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ingredients",
                    models.ManyToManyField(
                        related_name="recipes",
                        to="ingredients.ingredient",
                        verbose_name="Ингридиенты",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        related_name="recipes", to="tags.tag", verbose_name="Теги"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Рецепт",
                "ordering": ("-pub_date",),
                "default_related_name": "Рецепты",
            },
        ),
    ]
