# Generated by Django 4.2.9 on 2024-01-09 17:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="IngredientRecipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.SmallIntegerField(
                        help_text="Укажите количество ингредиента",
                        validators=[
                            django.core.validators.MinValueValidator(
                                1, message="Добавьте хотябы 1 ингредиент"
                            )
                        ],
                        verbose_name="Количество",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Добавьте фотографию",
                        upload_to="recipe/images/",
                        verbose_name="Фотография",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        error_messages={
                            "max_length": "Значение более 200 символов"
                        },
                        help_text="Укажите наименование",
                        max_length=200,
                        verbose_name="Наименование",
                    ),
                ),
                (
                    "text",
                    models.CharField(
                        help_text="Добавьте описание",
                        max_length=1000,
                        verbose_name="Описание",
                    ),
                ),
                (
                    "cooking_time",
                    models.IntegerField(
                        help_text="Укажите время приготовления",
                        validators=[
                            django.core.validators.MinValueValidator(
                                1,
                                message="Время приготовления не может быть менее 1 минуты",
                            )
                        ],
                        verbose_name="Время приготовления",
                    ),
                ),
                (
                    "pub_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата публикации"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Рецепт",
                "ordering": ("-pub_date",),
                "default_related_name": "Рецепты",
            },
        ),
    ]
