# Generated by Django 4.2.9 on 2024-01-07 09:18

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ingredients", "0001_initial"),
        ("recipes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="IngredientRecipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.SmallIntegerField(
                        help_text="Укажите количество ингредиента",
                        validators=[
                            django.core.validators.MinValueValidator(
                                1, message="Добавьте хотябы 1 ингредиент"
                            )
                        ],
                        verbose_name="Количество",
                    ),
                ),
                (
                    "ingredients",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ingredientrecipe",
                        to="ingredients.ingredient",
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ingredientrecipe",
                        to="recipes.recipe",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="ingredientrecipe",
            constraint=models.UniqueConstraint(
                fields=("recipe", "ingredients"), name="unique_recipe_ingredients"
            ),
        ),
    ]
