# Generated by Django 4.2.9 on 2024-01-10 12:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("recipes", "0007_alter_recipe_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShoppingcartRecipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="recipes.recipe",
                        verbose_name="Рецепт",
                    ),
                ),
                (
                    "shoppingcart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь(добавитель в корзину)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Рецепт для добавления в корзину",
                "verbose_name_plural": "Корзины",
            },
        ),
        migrations.AddConstraint(
            model_name="shoppingcartrecipe",
            constraint=models.UniqueConstraint(
                fields=("recipe", "shoppingcart"), name="unique_recipe_shoppingcart"
            ),
        ),
    ]
