# Generated by Django 4.2.9 on 2024-01-11 15:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("recipes", "0009_alter_shoppingcartrecipe_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shoppingcartrecipe",
            name="shoppingcart",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shopping_cart",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь(добавитель в корзину)",
            ),
        ),
    ]
