# Generated by Django 4.2.9 on 2024-01-11 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0010_alter_shoppingcartrecipe_shoppingcart"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shoppingcartrecipe",
            name="recipe",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shopping_cart",
                to="recipes.recipe",
                verbose_name="Рецепт",
            ),
        ),
    ]
