# Generated by Django 3.2.16 on 2024-01-16 06:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ingredients', '0002_alter_ingredient_options'),
        ('recipes', '0011_alter_shoppingcartrecipe_recipe'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='shoppingcartrecipe',
            name='unique_recipe_shoppingcart',
        ),
        migrations.RenameField(
            model_name='shoppingcartrecipe',
            old_name='shoppingcart',
            new_name='shopping_cart',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to=settings.AUTH_USER_MODEL, verbose_name='Авторы'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='recipes', through='recipes.IngredientRecipe', to='ingredients.Ingredient', verbose_name='Ингредиенты'),
        ),
        migrations.AddConstraint(
            model_name='shoppingcartrecipe',
            constraint=models.UniqueConstraint(fields=('recipe', 'shopping_cart'), name='unique_recipe_shopping_cart'),
        ),
    ]
