# Generated by Django 3.2.16 on 2024-01-16 06:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipes", "0012_auto_20240116_0919"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="ingredientrecipe",
            name="unique_recipe_ingredients",
        ),
        migrations.RenameField(
            model_name="ingredientrecipe",
            old_name="ingredients",
            new_name="ingredient",
        ),
        migrations.AddConstraint(
            model_name="ingredientrecipe",
            constraint=models.UniqueConstraint(
                fields=("recipe", "ingredient"),
                name="unique_recipe_ingredient",
            ),
        ),
    ]
