# Generated by Django 3.2.16 on 2024-01-17 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0014_auto_20240117_0647'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='favoriterecipe',
            name='unique_recipe_user',
        ),
        migrations.RemoveConstraint(
            model_name='shoppingcartrecipe',
            name='unique_recipe_shopping_cart',
        ),
        migrations.RenameField(
            model_name='shoppingcartrecipe',
            old_name='shopping_cart',
            new_name='user',
        ),
        migrations.AddConstraint(
            model_name='favoriterecipe',
            constraint=models.UniqueConstraint(fields=('recipe', 'user'), name='unique_recipe_favorite'),
        ),
        migrations.AddConstraint(
            model_name='shoppingcartrecipe',
            constraint=models.UniqueConstraint(fields=('recipe', 'user'), name='unique_recipe_shopping_cart'),
        ),
    ]
