# Generated by Django 4.2.9 on 2024-01-10 10:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscribe",
            name="subscriber",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscriber",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь на которого сделана подписка",
            ),
        ),
        migrations.AlterField(
            model_name="subscribe",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Текущий пользователь",
            ),
        ),
    ]
