# Generated by Django 3.2.16 on 2024-01-04 08:55

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_auto_20240104_1154"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="subscribe",
            name="Нельзя подписаться на самого себя",
        ),
        migrations.AddConstraint(
            model_name="subscribe",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("user", django.db.models.expressions.F("subscriber")),
                    _negated=True,
                ),
                name="prevent_subscribe_self",
            ),
        ),
    ]
