# Generated by Django 4.2.9 on 2024-01-05 13:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_auto_20240104_1155"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="subscribe",
            name="prevent_subscribe_self",
        ),
        migrations.AddConstraint(
            model_name="subscribe",
            constraint=models.CheckConstraint(
                check=models.Q(("user", models.F("subscriber")), _negated=True),
                name="Подписаться на самого себя нельзя",
            ),
        ),
    ]
